spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?characterEncoding=utf-8
    username: root
    password: cronaldo7
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置邮箱发送端
  mail:
    host: smtp.163.com
    username: m19925651773@163.com
    password: ZTREXUEQVBAJLDCW
    port: 465
    properties:
     from: m19925651773@163.com
     mail:
       smtp:
         socketFactory:
           class: javax.net.ssl.SSLSocketFactory
debug: true #开启日志
logging:
  level:
    com.xiaoRed: debug #设置日志级别
  # 配置Redis。不配也行，反正用的是本地的，就是默认配置
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
